services:
  client: 
    build: ./client/client
    ports:
      - 3000:3000
    volumes:
      - ./client/client/src/:/app/src/
  server:
    build: ./server
    ports: 
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db